version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      ruby: 2.6
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.....
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Building the Docker image.....
      - docker-compose -f docker-compose.yml build
      - docker tag my_first_server:latest 343700722017.dkr.ecr.ap-northeast-1.amazonaws.com/my_first_server:latest
      - docker tag my_first_web:latest 343700722017.dkr.ecr.ap-northeast-1.amazonaws.com/my_first_web:latest
  post_build:
    commands:
      - echo Posting the Docker image.....
      - docker push 343700722017.dkr.ecr.ap-northeast-1.amazonaws.com/my_first_server:latest
      - docker push 343700722017.dkr.ecr.ap-northeast-1.amazonaws.com/my_first_web:latest
