version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      ruby: 2.6
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Building the Docker images...
      - docker-compose build
      - echo Running RoR db:migrate...
      - docker-compose run --rm app rails db:migrate DB_DATABASE=$DB_DATABASE DB_USERNAME=$DB_USERNAME DB_PASSWORD=$DB_PASSWORD DB_HOST=$DB_HOST RAILS_ENV=$RAILS_ENV
      - docker tag $SERVER_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/$SERVER_REPO_NAME:$IMAGE_TAG
      - docker tag $WEB_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/$WEB_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Posting the Docker images...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/$SERVER_REPO_NAME:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/$WEB_REPO_NAME:$IMAGE_TAG
