version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - .mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  redis:
    image: redis:5.0.7
    volumes:
      - ".redis_data:/data"
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass foobared

  app:
    build:
      context: rails
    image: my_first_web
    volumes:
      - ./rails:/webapp
    links:
      - db
      - redis

  web:
    build:
      context: ./nginx/production
    image: my_first_server
    ports:
      - 80:80
    depends_on:
      - app
